"""add device browser and os

Revision ID: 0af4186ebe5a
Revises: 958d70a30990
Create Date: 2026-04-10 22:57:54.081537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af4186ebe5a'
down_revision: Union[str, Sequence[str], None] = '958d70a30990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_clicks', sa.Column('device', sa.String(), nullable=True))
    op.add_column('url_clicks', sa.Column('browser', sa.String(), nullable=True))
    op.add_column('url_clicks', sa.Column('os', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_clicks', 'os')
    op.drop_column('url_clicks', 'browser')
    op.drop_column('url_clicks', 'device')
    # ### end Alembic commands ###
