"""add analytics

Revision ID: 958d70a30990
Revises: 2beeb9e2add8
Create Date: 2026-04-10 21:03:23.631740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958d70a30990'
down_revision: Union[str, Sequence[str], None] = '2beeb9e2add8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_url_clicks_url_id_clicked_at', 'url_clicks', ['url_id', 'clicked_at'], unique=False)
    op.create_index(op.f('ix_url_clicks_id'), 'url_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_url_clicks_url_id'), 'url_clicks', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_clicks_url_id'), table_name='url_clicks')
    op.drop_index(op.f('ix_url_clicks_id'), table_name='url_clicks')
    op.drop_index('idx_url_clicks_url_id_clicked_at', table_name='url_clicks')
    op.drop_table('url_clicks')
    # ### end Alembic commands ###
