"""Some updates

Revision ID: 5c7c4261a1f6
Revises: 0af4186ebe5a
Create Date: 2026-04-14 02:16:21.819544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7c4261a1f6'
down_revision: Union[str, Sequence[str], None] = '0af4186ebe5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('url_clicks_url_id_fkey'), 'url_clicks', type_='foreignkey')
    op.create_foreign_key(None, 'url_clicks', 'urls', ['url_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('urls_user_id_fkey'), 'urls', type_='foreignkey')
    op.create_foreign_key(None, 'urls', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.create_foreign_key(op.f('urls_user_id_fkey'), 'urls', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'url_clicks', type_='foreignkey')
    op.create_foreign_key(op.f('url_clicks_url_id_fkey'), 'url_clicks', 'urls', ['url_id'], ['id'])
    # ### end Alembic commands ###
