"""Add create_at to urls

Revision ID: dc9a50b1c1b7
Revises: 5c7c4261a1f6
Create Date: 2026-04-15 18:22:11.758081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc9a50b1c1b7"
down_revision: Union[str, Sequence[str], None] = "5c7c4261a1f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "urls", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )

# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("urls", "created_at")
    # ### end Alembic commands ###
